# Generated by Django 4.2 on 2023-04-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0002_alter_category_options_alter_details_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
